# Generated by Django 4.2 on 2025-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, '先生'), (2, '生徒')], default=2, null=True, verbose_name='区分'),
        ),
    ]
