# Generated by Django 4.2 on 2025-08-10 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='学籍番号'),
        ),
    ]
