# Generated by Django 4.2 on 2025-08-17 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'username_unique': 'このユーザー名は既に使用されています。'}, help_text='必須です。150文字以内で入力してください。日本語も含めた文字、数字、@/./+/-/_ のみ使用できます。', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='username'),
        ),
    ]
