# Generated by Django 4.2 on 2025-08-07 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('place', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('charge_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('replacement_period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('reason', models.TextField()),
                ('cancel_date', models.DateField()),
                ('replacement_date', models.DateField()),
                ('original_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.period')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.subject'),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('leave_early', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='replacementinfo',
            constraint=models.UniqueConstraint(fields=('original_period', 'cancel_date', 'replacement_period'), name='cancel_unique'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'period', 'year', 'semester'), name='period_unique'),
        ),
        migrations.AddConstraint(
            model_name='attend',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='student_period_unique'),
        ),
    ]
