# Generated by Django 4.2 on 2025-09-04 06:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='曜日')),
                ('period', models.PositiveIntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='時間帯')),
                ('year', models.PositiveIntegerField(blank=True, default=2025, validators=[django.core.validators.MinValueValidator(2025)], verbose_name='年')),
                ('semester', models.IntegerField(choices=[(1, '前期'), (2, '後期')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='学期')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64, unique=True, verbose_name='教科名')),
                ('place', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='実施する教室')),
                ('charge_teacher', models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当教員')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_period', models.PositiveIntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='振替時間帯')),
                ('reason', models.TextField(verbose_name='理由')),
                ('replacement_date', models.DateField(blank=True, null=True, verbose_name='振替日')),
                ('cancel_date', models.DateField(verbose_name='元授業の日付')),
                ('original_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='元の授業')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject', verbose_name='教科'),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='打刻時間')),
                ('leave_early', models.BooleanField(default=False, verbose_name='早退フラグ')),
                ('period', models.ForeignKey(limit_choices_to={'year': 2025}, on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='授業')),
                ('student', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='生徒')),
            ],
        ),
        migrations.AddConstraint(
            model_name='replacementinfo',
            constraint=models.UniqueConstraint(fields=('original_period', 'cancel_date', 'replacement_period'), name='cancel_unique'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'period', 'year', 'semester', 'subject'), name='period_unique'),
        ),
        migrations.AddConstraint(
            model_name='attend',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='student_period_unique'),
        ),
    ]
