# Generated by Django 4.2 on 2025-08-10 04:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='leave_early',
            field=models.BooleanField(default=False, verbose_name='早退フラグ'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.period', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='生徒'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='打刻時間'),
        ),
        migrations.AlterField(
            model_name='period',
            name='day_of_week',
            field=models.PositiveIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.PositiveIntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='時間帯'),
        ),
        migrations.AlterField(
            model_name='period',
            name='semester',
            field=models.IntegerField(choices=[(1, '前期'), (2, '後期')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.subject', verbose_name='教科'),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025)], verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='cancel_date',
            field=models.DateField(verbose_name='振替日'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='original_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='元の授業'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='reason',
            field=models.TextField(verbose_name='理由'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='replacement_date',
            field=models.DateField(verbose_name='元授業の日付'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='replacement_day_of_week',
            field=models.PositiveIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='振替曜日'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='replacement_period',
            field=models.PositiveIntegerField(choices=[(1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='振替時間帯'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='charge_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当教員'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='place',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='実施する教室'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=64, verbose_name='教科名'),
        ),
    ]
