# Generated by Django 4.2 on 2025-07-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_user_email_alter_user_number_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
