# Generated by Django 4.2 on 2025-08-10 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attend_leave_early_alter_attend_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='place',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='実施する教室'),
        ),
    ]
