# Generated by Django 4.2 on 2025-08-10 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_subject_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='period',
            field=models.ForeignKey(limit_choices_to={'year': 2025}, on_delete=django.db.models.deletion.PROTECT, to='attendance.period', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='生徒'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='cancel_date',
            field=models.DateField(blank=True, null=True, verbose_name='振替日'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='charge_teacher',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当教員'),
        ),
    ]
