# Generated by Django 4.2 on 2025-08-10 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attend_period_alter_attend_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2025, validators=[django.core.validators.MinValueValidator(2025)], verbose_name='年(デフォルトは今の年)'),
        ),
    ]
