# Generated by Django 4.2 on 2025-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_period_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='period_unique',
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'period', 'year', 'semester', 'subject'), name='period_unique'),
        ),
    ]
