# Generated by Django 4.2 on 2025-08-17 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_period_period_unique_period_period_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2025, validators=[django.core.validators.MinValueValidator(2025)], verbose_name='年'),
        ),
    ]
