# Generated by Django 4.2 on 2025-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_period_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='period_unique',
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'period', 'year', 'semester', 'subject'), name='period_unique', violation_error_message='全く同じ組み合わせが既に登録されています。'),
        ),
    ]
