# Generated by Django 4.2 on 2025-08-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_period_period_unique_period_period_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='period_unique',
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject', verbose_name='教科'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'period', 'year', 'semester', 'subject'), name='period_unique'),
        ),
    ]
