# Generated by Django 4.2 on 2025-08-19 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0009_remove_period_period_unique_alter_period_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='period',
            field=models.ForeignKey(limit_choices_to={'year': 2025}, on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='授業'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='charge_teacher',
            field=models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当教員'),
        ),
    ]
