# Generated by Django 4.2 on 2025-08-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attend_period_alter_subject_charge_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='教科名'),
        ),
    ]
