# Generated by Django 4.2 on 2025-08-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementinfo',
            name='replacement_day_of_week',
        ),
    ]
