# Generated by Django 4.2 on 2025-08-22 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_replacementinfo_replacement_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementinfo',
            name='replacement_period',
            field=models.PositiveIntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='振替時間帯'),
        ),
    ]
