# Generated by Django 4.2 on 2025-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_replacementinfo_replacement_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementinfo',
            name='cancel_date',
            field=models.DateField(verbose_name='元授業の日付'),
        ),
        migrations.AlterField(
            model_name='replacementinfo',
            name='replacement_date',
            field=models.DateField(blank=True, null=True, verbose_name='振替日'),
        ),
    ]
